name: MD Converter

on:
  push:
    branches:
      - main
    paths:
      - "resume.md"
      - "assets/**"
      - "build.sh"
      - ".github/**"
      - "custom/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  convert:
    runs-on: ubuntu-22.04
    env:
      ENV: ci
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-1-amd64.deb
          sudo apt install -y ./pandoc-3.1.9-1-amd64.deb
      - name: Convert md to html and pdf
        run: ./build.sh
      - name: Setup gh pages
        uses: actions/configure-pages@v3
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: output/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
