name: Create PDF File

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2 # this checks out the repo in the ubuntu container
      # Downloading the binaries directly, because they are newer and work better, than the ones that come with Ubuntu latest.
      - name: Install pandoc and chromium
        run: |
          # TODO: install chromium
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
          sudo apt install ./pandoc-2.19.2-1-amd64.deb
      - name: Convert md to html and pdf
        run: ./build.sh
      - uses: actions/upload-artifact@master
        with: # basically this will put resume.md, resume.html, resume.pdf and resume-stylesheet.css in a zip file.
          name: ${{ github.actor }}'s Resume
          path: output
      # TODO: deploy content to clarkwinters.com
